### PR TITLE
Added tvOS target and scheme

### PR DESCRIPTION
**Pull request by pepibumur**
@LoganWright here I'm again :trollface: . I've added support for tvOS. I'm building a framework that is compatible for tvOS and couldn't build it because Genome didn't have support for tvOS yet.

### CODE REVIEW

**Comment by LoganWright** [comment]
@pepibumur Thanks again as always, but the work for this has actually already been done on the Xcode 7.1 branch.  I'm going to merge that into the project so the original contributor gets credit for his work :)

Let me know if it gives you any problems at all!!

**Comment by LoganWright** [comment]
See #15 and #23

**Comment by LoganWright** [comment]
@pepibumur Can you confirm if this is still an issue with the current master?

**Comment by pepibumur** [comment]
I installed it with Carthage and didn't have any problem @LoganWright , did you?

**Comment by LoganWright** [comment]
@pepibumur I did, but I think it was something else going on with my Carthage and wanted to verify that people who use carthage regularly are good to go.  Thanks for the response, I'll close this PR!

Thanks for your contributions as always!!!!!!!

**Pull request closed without merging**
