### PR TITLE
Carthage support

### PR DESCRIPTION
**Pull request by pepibumur**
## Done :white_check_mark: 
- [x] Updated README to include Carthage steps
- [x] Added new Framework target that compiles the source files into a framework
- [x] Shared the Framework scheme to be compilable by Carthage

### CODE REVIEW

**Comment by LoganWright** [comment]
Hi @pepibumur 

Thanks for the pull request, I think carthage support would be great!

I'm unfamiliar with some of the specifics pf Carthage, and I was wondering what the purpose of the additional Xcode Project is?  I was under the impression that Carthage didn't require any additional setup from a library's point of view in order to work.

I'll read up on a bit of carthage as well in the meantime!

Best,

Logan

**Comment by pepibumur** [comment]
Hi @LoganWright it's very simple how Carthage works:
1. Your project needs a Framework target that includes your source files and an Scheme that compiles that target. The result of compiling that scheme is a `.framework` file.
2. Carthage uses Github to resolve the dependencies, so it goes to the repository, clone it, and then look for a .xcodeproj or .xcworkspace file and compiles the shared schemes. The resulting frameworks are placed in a folder `/Carthage/Build`
3. Then you can integrate it into your project just dragging the .framework to the **Linked libraries** section in the Build settings.

The good point of your project is that it doesn't have any dependencies so the integration is even easier. If you want to know anything else let me know. I'm using it here https://github.com/SugarTeam/SoundCloudSwift . 
Thanks for the library, I was looking for something like this for a long time

**Comment by pepibumur** [comment]
BTW added missing targets for OS X and WatchOS @LoganWright

**Comment by pepibumur** [comment]
@LoganWright in fact there's only one project:
- The project includes three target (iOS/OSX/watchOSX)
- These three targets compile the frameworks for these three platforms.
- Each target include its testing framework.
- There're three schemes with the config to compile these frameworks

##### How to maintain it?
If you add a new .swift file to the project you have to make sure that the file is added to the three main targets, otherwise the compilation of these .frameworks will fail.

Thanks to you for doing this awesome stuff!

screen shot 2015-09-29 at 15 41 05

**Comment by LoganWright** [comment]
Awesome, this looks good then.  I'll make sure to add new files to the targets.  I might ping you again once tvOS is officially released to help me add that target as well!

Thanks for the contributions!

**Comment by sergigracia** [comment]
Great! Thanks @pepibumur :+1:

**Comment by pepibumur** [comment]
Nice, thanks @LoganWright integrated it using Carthage and didn't have any problem. Nice job!

**Comment by pepibumur** [comment]
@LoganWright remember to create a new Release so Carthage can use it as the last available version :)

**Comment by LoganWright** [comment]
@pepibumur Didn't realize it needed a new release, I'll mark it right now!  Thanks for all of this, I'm sure carthage users definitely appreciate people like you helping to get it all setup!

**Pull request merged**
