### PR TITLE
File Type Independence 

### PR DESCRIPTION
**Pull request by Marxon13**
I've started working on the changes we discussed over email. I've removed the `Json` type and replaced it with a file type independent structure `Dna`. I've updated all the project files, tests, and README to reflect this. 

I'm not exactly sure about calling the new object `Dna`, it might be a bit too confusing. Perhaps `Object` is another possibility? I tried `Element` and it conflicts with Swift's `Element`

### CODE REVIEW

**Comment by justbaum30** [comment]
I would say the `Dna` name is confusing. I would definitely prefer `Object`. Just out of curiosity, are you guys hoping that this could lead to serializing/deserializing formats like XML? My main concern would be harder maintainability/complexity whereas currently this is a nice, light, specialized library.

**Comment by Marxon13** [comment]
I'll try object. I tried `Element`, but it conflicts with Swift Array's `Element`. 

Personally I am hoping Genome can be in a place where it can be used to serialize/deserialize any file type (JSON, XML, ...) and provide a common interface to do so. I know @LoganWright has thought about the same thing, but has not had the time to pursue it. To do that, I figured the Json dependency should be separated from the "Core" of the project. Then be "re-added" as a JSON specific serializer/deserializer.

I was thinking the project could be set up so that each file type serializer would be included only if it was needed. Since Cocoapods can have a base pod of Genome, then sub pods for each file type serializer. That way everyone can just use the pod for the file types they need if any. I'm not sure if the swift package manager has similar functionality, that will have to be looked into.

The serializers could be kept in this repository, or in a separate repository that links to Genome.

**Comment by Marxon13** [comment]
@justbaum30 `Object` would work, I would just need to rename the `Object` class in MappableObject.swift.

**Comment by justbaum30** [comment]
Yeah, if you guys plan on going this route definitely +1 the separate pods. Not sure that I have a particular name in mind, I'm just not a fan of `Dna`.

On a more related note to the Genome 2.0 release (using the `PureJson` library) and possibly implementing other serializers such as XML, I would recommend keeping tabs on what's upcoming with Swift 3.0. They are porting over basically the entire `Foundation` library to Swift so it would be cross-platform. [You can check out their progress here.](https://github.com/apple/swift-corelibs-foundation/blob/master/Docs/Status.md) 

As you can see, they are going to be adding support for XML, Json, NSData, etc. parsing/validation. Obviously this isn't going to be released until Fall, but when it does get released, I'm assuming you'd want Genome to use the native APIs. It will keep Genome Linux-compatible and not force you to re-invent the wheel.

**Comment by Marxon13** [comment]
@justbaum30 I'm thinking either `Item` or `Atom`. I like `Atom` a bit more as it is harder to confuse when talking about it, as well as a bit more fun. Man, I've never had this much trouble naming things before. Phil Karlton was right.

**Comment by LoganWright** [comment]
@Marxon13 @justbaum30 

Great conversation around this, I'm backed up on client work today, so I haven't gotten a chance to run a review, but I think there's a lot of good points.  I will do my best to read more thoroughly and give good thoughts in the next day or two.

On Foundation / PureJsonSerializer

I would definitely like to stay within foundation as they ramp up support.  Ideally if we make a good data abstraction layer, these would be easy to integrate in place of the pure json serializer or whatever other layers are involved.

On Multiple Pods

100% on board for subspecs.  Right now, I'm picturing the library will probably have  its default set to Json, so if the user only rights `pod 'Genome'`, it will include Json by default.  Otherwise, I'd imagine it would be `pod 'Genome/Stripped'`, `pod 'Genome/XML'` etc.  Not sure the implications of this on Carthage, but I'm personally content with relying on the carthage community to add support for what they need as they need it.

Thanks for all the contributions guys, I'm looking forward to seeing how this progresses.

Best,

Logan

**Comment by LoganWright** [comment]
Closed for #51

**Pull request closed without merging**
